//
//  QuestCatalog.swift
//  benk
//
//  Quest definitions - 20 daily, 20 weekly, 20 goal templates
//

import Foundation

struct QuestCatalog {
    
    // MARK: - Daily Quests (50-100 coins)
    static let dailyQuests: [QuestTemplate] = [
        QuestTemplate(
            id: "daily_tasks_3",
            title: "Task Starter",
            description: "Complete 3 tasks today",
            instructions: "Mark any 3 tasks as complete in your task list. Each task you finish counts!",
            lore: "Every journey begins with a single step. The Scholar's Path teaches us that consistent small actions build mighty achievements.",
            icon: "checkmark.circle.fill",
            category: .daily,
            trackingType: .tasksCompletedToday,
            targetValue: 3,
            coinReward: 50,
            colorHex: "#4CAF50"
        ),
        QuestTemplate(
            id: "daily_tasks_5",
            title: "Task Warrior",
            description: "Complete 5 tasks today",
            instructions: "Complete 5 tasks from your task list. Break larger tasks into smaller ones if needed!",
            lore: "The ancient scholars believed that five represents the balance of the elements. Master five tasks, master your day.",
            icon: "checkmark.circle.fill",
            category: .daily,
            trackingType: .tasksCompletedToday,
            targetValue: 5,
            coinReward: 70,
            colorHex: "#4CAF50"
        ),
        QuestTemplate(
            id: "daily_tasks_10",
            title: "Task Master",
            description: "Complete 10 tasks today",
            instructions: "A productive day awaits! Complete 10 tasks to prove your dedication.",
            lore: "Legend speaks of the Ten-Task Masters who could reshape their destiny in a single day. Will you join their ranks?",
            icon: "checkmark.circle.fill",
            category: .daily,
            trackingType: .tasksCompletedToday,
            targetValue: 10,
            coinReward: 100,
            colorHex: "#4CAF50"
        ),
        QuestTemplate(
            id: "daily_study_30",
            title: "Quick Study",
            description: "Study for 30 minutes",
            instructions: "Start a study session and focus for at least 30 minutes total today.",
            lore: "Half an hour of focused learning compounds into wisdom over time. The Library awaits your presence.",
            icon: "book.fill",
            category: .daily,
            trackingType: .studyMinutesToday,
            targetValue: 30,
            coinReward: 50,
            colorHex: "#2196F3"
        ),
        QuestTemplate(
            id: "daily_study_60",
            title: "Hour of Power",
            description: "Study for 1 hour",
            instructions: "Dedicate one full hour to studying today. You can split it across multiple sessions.",
            lore: "An hour of study is worth a thousand hours of regret. The wise invest their time like precious gems.",
            icon: "book.fill",
            category: .daily,
            trackingType: .studyMinutesToday,
            targetValue: 60,
            coinReward: 70,
            colorHex: "#2196F3"
        ),
        QuestTemplate(
            id: "daily_study_120",
            title: "Deep Focus",
            description: "Study for 2 hours",
            instructions: "Challenge yourself with 2 hours of study today. Take breaks as needed!",
            lore: "Two hours of deep focus unlocks the deepest chambers of the Mind Palace. Few dare to venture so far.",
            icon: "book.fill",
            category: .daily,
            trackingType: .studyMinutesToday,
            targetValue: 120,
            coinReward: 100,
            colorHex: "#2196F3"
        ),
        QuestTemplate(
            id: "daily_goal",
            title: "Goal Crusher",
            description: "Complete your daily study goal",
            instructions: "Study enough to fill your daily goal meter. Check your progress in the home view!",
            lore: "Daily goals are the stepping stones across the river of achievement. Miss one, and the waters grow turbulent.",
            icon: "target",
            category: .daily,
            trackingType: .dailyGoalCompleted,
            targetValue: 1,
            coinReward: 80,
            colorHex: "#FF9800"
        ),
        QuestTemplate(
            id: "daily_subjects_2",
            title: "Subject Explorer",
            description: "Study 2 different subjects",
            instructions: "Switch between at least 2 different subjects during your study sessions today.",
            lore: "The Renaissance scholars knew that cross-pollination of knowledge breeds genius. Explore broadly!",
            icon: "books.vertical.fill",
            category: .daily,
            trackingType: .subjectsStudiedToday,
            targetValue: 2,
            coinReward: 60,
            colorHex: "#9C27B0"
        ),
        QuestTemplate(
            id: "daily_subjects_3",
            title: "Subject Hopper",
            description: "Study 3 different subjects",
            instructions: "Balance your learning by studying 3 different subjects today.",
            lore: "Three subjects form a triangle of knowledge - the most stable foundation for any scholar.",
            icon: "books.vertical.fill",
            category: .daily,
            trackingType: .subjectsStudiedToday,
            targetValue: 3,
            coinReward: 80,
            colorHex: "#9C27B0"
        ),
        QuestTemplate(
            id: "daily_break",
            title: "Rest & Recharge",
            description: "Take a break",
            instructions: "Use the break timer to take at least one proper break during your study session.",
            lore: "Even the mightiest minds need rest. The Zen Gardens of the Academy offer peace to weary scholars.",
            icon: "cup.and.saucer.fill",
            category: .daily,
            trackingType: .breaksTakenToday,
            targetValue: 1,
            coinReward: 50,
            colorHex: "#00BCD4"
        ),
        QuestTemplate(
            id: "daily_pomodoro_1",
            title: "Pomodoro Starter",
            description: "Complete a Pomodoro session",
            instructions: "Use the Pomodoro timer mode and complete one full focus session.",
            lore: "The Pomodoro technique was discovered in ancient tomato gardens. Its power over time is legendary.",
            icon: "timer",
            category: .daily,
            trackingType: .pomodorosCompletedToday,
            targetValue: 1,
            coinReward: 60,
            colorHex: "#F44336"
        ),
        QuestTemplate(
            id: "daily_pomodoro_2",
            title: "Pomodoro Pair",
            description: "Complete 2 Pomodoro sessions",
            instructions: "Complete 2 full Pomodoro sessions today. Stay focused!",
            lore: "Two pomodoros form a bond stronger than one. The rhythm of focus and rest becomes music.",
            icon: "timer",
            category: .daily,
            trackingType: .pomodorosCompletedToday,
            targetValue: 2,
            coinReward: 80,
            colorHex: "#F44336"
        ),
        QuestTemplate(
            id: "daily_session",
            title: "Focus Session",
            description: "Complete a study session",
            instructions: "Start and complete any study session, regardless of duration.",
            lore: "A single session creates a ripple in the ocean of knowledge. Begin, and the waves will carry you.",
            icon: "play.circle.fill",
            category: .daily,
            trackingType: .studySessionCompleted,
            targetValue: 1,
            coinReward: 50,
            colorHex: "#673AB7"
        ),
        QuestTemplate(
            id: "daily_early",
            title: "Early Bird",
            description: "Study before 9 AM",
            instructions: "Start a study session before 9:00 AM. Morning study supercharges your brain!",
            lore: "The dawn scholars claim the freshest knowledge. While others sleep, the wise ones grow.",
            icon: "sunrise.fill",
            category: .daily,
            trackingType: .earlyMorningStudy,
            targetValue: 1,
            coinReward: 60,
            colorHex: "#FFC107"
        ),
        QuestTemplate(
            id: "daily_evening",
            title: "Night Owl",
            description: "Study after 6 PM",
            instructions: "Have a study session in the evening, after 6:00 PM.",
            lore: "When the moon rises, the Night Academy opens its doors. Secrets are best learned by starlight.",
            icon: "moon.fill",
            category: .daily,
            trackingType: .eveningStudy,
            targetValue: 1,
            coinReward: 60,
            colorHex: "#3F51B5"
        ),
        QuestTemplate(
            id: "daily_pomodoro_3",
            title: "Pomodoro Triple",
            description: "Complete 3 Pomodoro sessions",
            instructions: "Master your focus with 3 complete Pomodoro sessions today.",
            lore: "Three pomodoros form the sacred triangle of productivity. Ancient scholars called this the Triforce of Focus.",
            icon: "timer",
            category: .daily,
            trackingType: .pomodorosCompletedToday,
            targetValue: 3,
            coinReward: 100,
            colorHex: "#F44336"
        ),
        QuestTemplate(
            id: "daily_breaks_3",
            title: "Balanced Day",
            description: "Take 3 breaks",
            instructions: "Remember to rest! Take 3 proper breaks during your study sessions.",
            lore: "The Rule of Three Rests ensures the mind stays sharp. Even blades need sharpening.",
            icon: "cup.and.saucer.fill",
            category: .daily,
            trackingType: .breaksTakenToday,
            targetValue: 3,
            coinReward: 70,
            colorHex: "#00BCD4"
        ),
        QuestTemplate(
            id: "daily_study_15",
            title: "Quick Sprint",
            description: "Study for 15 minutes",
            instructions: "Just 15 minutes of focused study. Perfect for a quick learning burst!",
            lore: "A quarter hour of focus can change your entire day. Small commitments yield mighty results.",
            icon: "bolt.fill",
            category: .daily,
            trackingType: .studyMinutesToday,
            targetValue: 15,
            coinReward: 50,
            colorHex: "#FFEB3B"
        ),
        QuestTemplate(
            id: "daily_exceed_goal",
            title: "Overachiever",
            description: "Exceed daily goal by 30 min",
            instructions: "Go beyond your daily goal! Study 30 minutes more than your target.",
            lore: "Those who exceed expectations write their names in the Hall of Legends. Dare to go further!",
            icon: "arrow.up.circle.fill",
            category: .daily,
            trackingType: .exceedDailyGoal,
            targetValue: 30,
            coinReward: 100,
            colorHex: "#E91E63"
        ),
        QuestTemplate(
            id: "daily_tasks_7",
            title: "Lucky Seven",
            description: "Complete 7 tasks today",
            instructions: "Seven tasks for a lucky day! Check off 7 items from your task list.",
            lore: "Seven is the number of completion. The Seven Sages completed seven tasks each day without fail.",
            icon: "checkmark.circle.fill",
            category: .daily,
            trackingType: .tasksCompletedToday,
            targetValue: 7,
            coinReward: 85,
            colorHex: "#4CAF50"
        ),
    ]
    
    // MARK: - Weekly Quests (150-350 coins)
    static let weeklyQuests: [QuestTemplate] = [
        QuestTemplate(
            id: "weekly_tasks_20",
            title: "Weekly Warrior",
            description: "Complete 20 tasks this week",
            instructions: "Stay consistent and complete 20 tasks throughout the week.",
            lore: "Twenty tasks mark the difference between a student and a scholar. The weekly warriors never falter.",
            icon: "checkmark.seal.fill",
            category: .weekly,
            trackingType: .tasksCompletedThisWeek,
            targetValue: 20,
            coinReward: 150,
            colorHex: "#4CAF50"
        ),
        QuestTemplate(
            id: "weekly_tasks_50",
            title: "Task Champion",
            description: "Complete 50 tasks this week",
            instructions: "An ambitious goal! Complete 50 tasks over the course of this week.",
            lore: "Fifty tasks echo like fifty bells in the Tower of Achievement. Their sound reaches the heavens.",
            icon: "checkmark.seal.fill",
            category: .weekly,
            trackingType: .tasksCompletedThisWeek,
            targetValue: 50,
            coinReward: 250,
            colorHex: "#4CAF50"
        ),
        QuestTemplate(
            id: "weekly_tasks_100",
            title: "Century Master",
            description: "Complete 100 tasks this week",
            instructions: "The ultimate task challenge! Complete 100 tasks in a single week.",
            lore: "A century of tasks! Only the most dedicated reach this pinnacle. Your name shall be etched in crystal.",
            icon: "checkmark.seal.fill",
            category: .weekly,
            trackingType: .tasksCompletedThisWeek,
            targetValue: 100,
            coinReward: 350,
            colorHex: "#4CAF50"
        ),
        QuestTemplate(
            id: "weekly_study_5h",
            title: "5-Hour Scholar",
            description: "Study 5 hours this week",
            instructions: "Accumulate 5 hours of study time across all your sessions this week.",
            lore: "Five hours open the first gate of weekly wisdom. The journey of a thousand hours begins here.",
            icon: "clock.fill",
            category: .weekly,
            trackingType: .studyMinutesThisWeek,
            targetValue: 300,
            coinReward: 150,
            colorHex: "#2196F3"
        ),
        QuestTemplate(
            id: "weekly_study_10h",
            title: "10-Hour Hero",
            description: "Study 10 hours this week",
            instructions: "Dedicate 10 hours to learning this week. Average about 1.5 hours per day!",
            lore: "Ten hours transform potential into power. The Heroes of Learning reached this milestone every week.",
            icon: "clock.fill",
            category: .weekly,
            trackingType: .studyMinutesThisWeek,
            targetValue: 600,
            coinReward: 200,
            colorHex: "#2196F3"
        ),
        QuestTemplate(
            id: "weekly_study_20h",
            title: "20-Hour Legend",
            description: "Study 20 hours this week",
            instructions: "An impressive 20 hours of study! That's nearly 3 hours per day.",
            lore: "Twenty hours forge a legend. The Grand Library only admits those who have proven such dedication.",
            icon: "clock.fill",
            category: .weekly,
            trackingType: .studyMinutesThisWeek,
            targetValue: 1200,
            coinReward: 300,
            colorHex: "#2196F3"
        ),
        QuestTemplate(
            id: "weekly_study_30h",
            title: "30-Hour Sage",
            description: "Study 30 hours this week",
            instructions: "The ultimate study challenge! 30 hours of focused learning in one week.",
            lore: "Only the Sages of the Inner Circle achieve such mastery. You approach enlightenment itself.",
            icon: "clock.fill",
            category: .weekly,
            trackingType: .studyMinutesThisWeek,
            targetValue: 1800,
            coinReward: 350,
            colorHex: "#2196F3"
        ),
        QuestTemplate(
            id: "weekly_goals_3",
            title: "Goal Streak",
            description: "Complete daily goal 3 days",
            instructions: "Hit your daily study goal on at least 3 different days this week.",
            lore: "Three days of goal completion form a streak of power. The energy compounds!",
            icon: "flame.fill",
            category: .weekly,
            trackingType: .dailyGoalsCompletedThisWeek,
            targetValue: 3,
            coinReward: 180,
            colorHex: "#FF9800"
        ),
        QuestTemplate(
            id: "weekly_goals_5",
            title: "Goal Champion",
            description: "Complete daily goal 5 days",
            instructions: "Maintain your momentum! Hit your daily goal on 5 different days.",
            lore: "Five days of goals touched is a hand of victory. Grasp your success!",
            icon: "flame.fill",
            category: .weekly,
            trackingType: .dailyGoalsCompletedThisWeek,
            targetValue: 5,
            coinReward: 250,
            colorHex: "#FF9800"
        ),
        QuestTemplate(
            id: "weekly_goals_7",
            title: "Perfect Week",
            description: "Complete daily goal every day",
            instructions: "The ultimate achievement! Hit your daily goal all 7 days of the week.",
            lore: "A perfect week is spoken of in whispers. Few achieve it. Will you join their ranks?",
            icon: "flame.fill",
            category: .weekly,
            trackingType: .dailyGoalsCompletedThisWeek,
            targetValue: 7,
            coinReward: 350,
            colorHex: "#FF9800"
        ),
        QuestTemplate(
            id: "weekly_streak_3",
            title: "Streak Builder",
            description: "Maintain a 3-day streak",
            instructions: "Keep your study streak alive for at least 3 consecutive days.",
            lore: "Three days ignite the spark of habit. Guard this flame carefully!",
            icon: "bolt.fill",
            category: .weekly,
            trackingType: .streakDays,
            targetValue: 3,
            coinReward: 150,
            colorHex: "#E91E63"
        ),
        QuestTemplate(
            id: "weekly_streak_5",
            title: "Streak Keeper",
            description: "Maintain a 5-day streak",
            instructions: "Your streak is your legacy! Keep it going for 5 days.",
            lore: "Five days forge a chain of discipline. Each link makes you stronger.",
            icon: "bolt.fill",
            category: .weekly,
            trackingType: .streakDays,
            targetValue: 5,
            coinReward: 220,
            colorHex: "#E91E63"
        ),
        QuestTemplate(
            id: "weekly_streak_7",
            title: "Streak Master",
            description: "Maintain a 7-day streak",
            instructions: "A full week without breaking your streak! Legendary dedication.",
            lore: "Seven days of unbroken commitment! The Streak Masters bow to your perseverance.",
            icon: "bolt.fill",
            category: .weekly,
            trackingType: .streakDays,
            targetValue: 7,
            coinReward: 300,
            colorHex: "#E91E63"
        ),
        QuestTemplate(
            id: "weekly_pomodoro_10",
            title: "Pomodoro Pack",
            description: "Complete 10 Pomodoro sessions",
            instructions: "Use the Pomodoro timer for 10 complete sessions this week.",
            lore: "Ten pomodoros ripen into a harvest of knowledge. The Tomato Gardens overflow!",
            icon: "timer",
            category: .weekly,
            trackingType: .pomodorosCompletedThisWeek,
            targetValue: 10,
            coinReward: 200,
            colorHex: "#F44336"
        ),
        QuestTemplate(
            id: "weekly_breaks_10",
            title: "Well Rested",
            description: "Take 10 breaks",
            instructions: "Remember to rest! Take 10 proper breaks throughout the week.",
            lore: "Ten moments of rest weave a safety net for your mind. The wise know when to pause.",
            icon: "cup.and.saucer.fill",
            category: .weekly,
            trackingType: .breaksTakenThisWeek,
            targetValue: 10,
            coinReward: 150,
            colorHex: "#00BCD4"
        ),
        QuestTemplate(
            id: "weekly_weekend",
            title: "Weekend Scholar",
            description: "Study on a weekend",
            instructions: "Complete at least one study session on Saturday or Sunday.",
            lore: "While others rest, the Weekend Scholars advance. The weekend holds hidden wisdom.",
            icon: "sun.max.fill",
            category: .weekly,
            trackingType: .weekendStudy,
            targetValue: 1,
            coinReward: 180,
            colorHex: "#FFC107"
        ),
        QuestTemplate(
            id: "weekly_tasks_day_15",
            title: "Productive Day",
            description: "Complete 15 tasks in one day",
            instructions: "Have an extremely productive day with 15 completed tasks!",
            lore: "Fifteen tasks in a single sun cycle! The Day Champions achieve this feat of focus.",
            icon: "star.fill",
            category: .weekly,
            trackingType: .tasksInOneDay,
            targetValue: 15,
            coinReward: 200,
            colorHex: "#9C27B0"
        ),
        QuestTemplate(
            id: "weekly_study_day_4h",
            title: "Marathon Day",
            description: "Study 4 hours in one day",
            instructions: "Have an intensive study day with 4 hours of total study time.",
            lore: "Four hours in a single day! The Marathon Scholars push through to glory.",
            icon: "figure.run",
            category: .weekly,
            trackingType: .studyMinutesInOneDay,
            targetValue: 240,
            coinReward: 180,
            colorHex: "#673AB7"
        ),
        QuestTemplate(
            id: "weekly_challenges_3",
            title: "Challenge Hunter",
            description: "Complete daily challenges 3 days",
            instructions: "Complete all 3 daily challenges on 3 different days this week.",
            lore: "The Challenge Hunters leave no stone unturned. Their dedication echoes through the halls.",
            icon: "trophy.fill",
            category: .weekly,
            trackingType: .dailyChallengesCompletedThisWeek,
            targetValue: 3,
            coinReward: 350,
            colorHex: "#FFD700"
        ),
        QuestTemplate(
            id: "weekly_pomodoro_20",
            title: "Pomodoro Master",
            description: "Complete 20 Pomodoro sessions",
            instructions: "Become a true Pomodoro master with 20 sessions this week!",
            lore: "Twenty pomodoros crown you as a Master. The Tomato Temple awaits your arrival.",
            icon: "timer",
            category: .weekly,
            trackingType: .pomodorosCompletedThisWeek,
            targetValue: 20,
            coinReward: 300,
            colorHex: "#F44336"
        ),
    ]
    
    // MARK: - Goals (50-350 coins, based on achievements)
    static let goalQuests: [QuestTemplate] = [
        QuestTemplate(
            id: "goal_pet_1",
            title: "First Friend",
            description: "Own 1 pet",
            instructions: "Visit the shop and purchase your first pet companion!",
            lore: "Every scholar needs a faithful companion. Pets in the Academy have been known to boost focus and morale.",
            icon: "pawprint.fill",
            category: .goals,
            trackingType: .petsOwned,
            targetValue: 1,
            coinReward: 50,
            colorHex: "#795548"
        ),
        QuestTemplate(
            id: "goal_pet_5",
            title: "Pet Collector",
            description: "Own 5 pets",
            instructions: "Expand your pet family! Purchase 5 different pets from the shop.",
            lore: "Five pets form a Fellowship of Focus. Together, they guard your concentration with fierce loyalty.",
            icon: "pawprint.fill",
            category: .goals,
            trackingType: .petsOwned,
            targetValue: 5,
            coinReward: 150,
            colorHex: "#795548"
        ),
        QuestTemplate(
            id: "goal_plant_3",
            title: "Green Thumb",
            description: "Own 3 plants",
            instructions: "Add some life to your room! Purchase 3 plant decorations.",
            lore: "Plants in the Study Garden are said to absorb negative thoughts and breathe out inspiration.",
            icon: "leaf.fill",
            category: .goals,
            trackingType: .plantsOwned,
            targetValue: 3,
            coinReward: 75,
            colorHex: "#4CAF50"
        ),
        QuestTemplate(
            id: "goal_plant_10",
            title: "Botanist",
            description: "Own 10 plants",
            instructions: "Create your own botanical garden! Collect 10 plant items.",
            lore: "The Academy's Greenhouse holds ten legendary plants. Collect them all to unlock their secret wisdom.",
            icon: "leaf.fill",
            category: .goals,
            trackingType: .plantsOwned,
            targetValue: 10,
            coinReward: 150,
            colorHex: "#4CAF50"
        ),
        QuestTemplate(
            id: "goal_furniture_5",
            title: "Interior Starter",
            description: "Own 5 furniture items",
            instructions: "Begin furnishing your room with 5 pieces of furniture.",
            lore: "A well-furnished room is a well-prepared mind. The first five pieces set the foundation.",
            icon: "chair.fill",
            category: .goals,
            trackingType: .furnitureOwned,
            targetValue: 5,
            coinReward: 50,
            colorHex: "#8D6E63"
        ),
        QuestTemplate(
            id: "goal_furniture_25",
            title: "Furniture Enthusiast",
            description: "Own 25 furniture items",
            instructions: "Build an impressive furniture collection with 25 pieces!",
            lore: "Twenty-five pieces of furniture transform a room into a sanctuary. The Comfort Council approves.",
            icon: "chair.fill",
            category: .goals,
            trackingType: .furnitureOwned,
            targetValue: 25,
            coinReward: 200,
            colorHex: "#8D6E63"
        ),
        QuestTemplate(
            id: "goal_items_50",
            title: "Collector's Pride",
            description: "Own 50 items total",
            instructions: "Amass a collection of 50 items in your inventory.",
            lore: "Fifty items mark you as a true Collector. The Curator's Guild welcomes your dedication.",
            icon: "archivebox.fill",
            category: .goals,
            trackingType: .itemsOwned,
            targetValue: 50,
            coinReward: 250,
            colorHex: "#607D8B"
        ),
        QuestTemplate(
            id: "goal_place_5",
            title: "Room Decorator",
            description: "Place 5 items in your room",
            instructions: "Decorate your room by placing 5 items from your inventory.",
            lore: "Five placed items transform an empty space into a home. Your journey as a decorator begins!",
            icon: "square.grid.2x2.fill",
            category: .goals,
            trackingType: .itemsPlaced,
            targetValue: 5,
            coinReward: 50,
            colorHex: "#9E9E9E"
        ),
        QuestTemplate(
            id: "goal_place_25",
            title: "Interior Designer",
            description: "Place 25 items in your room",
            instructions: "Create a fully decorated space with 25 placed items!",
            lore: "Twenty-five placed items create a masterpiece. The Design Guild nominates you for membership.",
            icon: "square.grid.2x2.fill",
            category: .goals,
            trackingType: .itemsPlaced,
            targetValue: 25,
            coinReward: 150,
            colorHex: "#9E9E9E"
        ),
        QuestTemplate(
            id: "goal_place_50",
            title: "Master Decorator",
            description: "Place 50 items in your room",
            instructions: "Fill your room to the brim! Place 50 items for the ultimate decorated space.",
            lore: "Fifty items placed with intention create a Palace of Productivity. Legends are born here.",
            icon: "square.grid.2x2.fill",
            category: .goals,
            trackingType: .itemsPlaced,
            targetValue: 50,
            coinReward: 300,
            colorHex: "#9E9E9E"
        ),
        QuestTemplate(
            id: "goal_coins_500",
            title: "Coin Starter",
            description: "Earn 500 coins total",
            instructions: "Accumulate 500 coins through studying and completing quests.",
            lore: "Five hundred coins mark your first treasure. The path to wealth begins with a single coin.",
            icon: "dollarsign.circle.fill",
            category: .goals,
            trackingType: .coinsEarned,
            targetValue: 500,
            coinReward: 50,
            colorHex: "#FFD700"
        ),
        QuestTemplate(
            id: "goal_coins_1000",
            title: "Thousand Club",
            description: "Earn 1,000 coins total",
            instructions: "Reach the prestigious 1,000 coin milestone!",
            lore: "A thousand coins! The Merchant's Guild takes notice. Your dedication yields golden rewards.",
            icon: "dollarsign.circle.fill",
            category: .goals,
            trackingType: .coinsEarned,
            targetValue: 1000,
            coinReward: 100,
            colorHex: "#FFD700"
        ),
        QuestTemplate(
            id: "goal_coins_5000",
            title: "Wealthy Scholar",
            description: "Earn 5,000 coins total",
            instructions: "Amass a fortune of 5,000 coins through your hard work!",
            lore: "Five thousand coins! The Treasury Guard salutes your achievement. Wealth follows wisdom.",
            icon: "dollarsign.circle.fill",
            category: .goals,
            trackingType: .coinsEarned,
            targetValue: 5000,
            coinReward: 200,
            colorHex: "#FFD700"
        ),
        QuestTemplate(
            id: "goal_coins_10000",
            title: "Coin Tycoon",
            description: "Earn 10,000 coins total",
            instructions: "Join the elite! Earn a total of 10,000 coins.",
            lore: "Ten thousand coins crown you as a Tycoon. The Golden Council offers you a seat at their table.",
            icon: "dollarsign.circle.fill",
            category: .goals,
            trackingType: .coinsEarned,
            targetValue: 10000,
            coinReward: 300,
            colorHex: "#FFD700"
        ),
        QuestTemplate(
            id: "goal_decor_3",
            title: "Decoration Dabbler",
            description: "Own 3 decorations",
            instructions: "Add some flair! Purchase 3 decoration items.",
            lore: "Three decorations brighten any room. The Aesthetic Society welcomes new members!",
            icon: "sparkles",
            category: .goals,
            trackingType: .decorationsOwned,
            targetValue: 3,
            coinReward: 75,
            colorHex: "#E91E63"
        ),
        QuestTemplate(
            id: "goal_decor_10",
            title: "Decoration Expert",
            description: "Own 10 decorations",
            instructions: "Build a collection of 10 beautiful decorations.",
            lore: "Ten decorations transform spaces into experiences. The Art Council takes notice.",
            icon: "sparkles",
            category: .goals,
            trackingType: .decorationsOwned,
            targetValue: 10,
            coinReward: 150,
            colorHex: "#E91E63"
        ),
        QuestTemplate(
            id: "goal_themes_3",
            title: "Theme Explorer",
            description: "Try 3 room themes",
            instructions: "Experiment with 3 different room theme styles.",
            lore: "Three themes broaden your horizons. The Style Explorers honor those who dare to change.",
            icon: "paintpalette.fill",
            category: .goals,
            trackingType: .roomThemesUsed,
            targetValue: 3,
            coinReward: 100,
            colorHex: "#9C27B0"
        ),
        QuestTemplate(
            id: "goal_streak_10",
            title: "Streak Warrior",
            description: "Reach a 10-day streak",
            instructions: "Maintain your study streak for 10 consecutive days!",
            lore: "Ten days of unbroken dedication! The Streak Warriors initiate you into their order.",
            icon: "flame.fill",
            category: .goals,
            trackingType: .currentStreak,
            targetValue: 10,
            coinReward: 200,
            colorHex: "#FF5722"
        ),
        QuestTemplate(
            id: "goal_tasks_100",
            title: "Century Achiever",
            description: "Complete 100 tasks total",
            instructions: "Reach the milestone of 100 completed tasks across all time!",
            lore: "One hundred tasks completed! The Achiever's Hall immortalizes your dedication in stone.",
            icon: "checkmark.seal.fill",
            category: .goals,
            trackingType: .tasksCompletedTotal,
            targetValue: 100,
            coinReward: 250,
            colorHex: "#4CAF50"
        ),
        QuestTemplate(
            id: "goal_study_3000",
            title: "50-Hour Scholar",
            description: "Study 50 hours total",
            instructions: "Accumulate 50 hours of study time. A true milestone of dedication!",
            lore: "Fifty hours of study! The Grand Archives inscribe your name among the dedicated learners.",
            icon: "brain.head.profile",
            category: .goals,
            trackingType: .studyMinutesTotal,
            targetValue: 3000,
            coinReward: 350,
            colorHex: "#3F51B5"
        ),
    ]
    
    // MARK: - Helpers
    
    static var allQuests: [QuestTemplate] {
        dailyQuests + weeklyQuests + goalQuests
    }
    
    static func getTemplate(id: String) -> QuestTemplate? {
        allQuests.first { $0.id == id }
    }
}
